# Generated by Django 4.1.3 on 2022-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mov',
            name='image',
            field=models.ImageField(default='asdgd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
